const {
    DB_USERNAME,
    DB_PASSWORD,
    DB_NAME,
    MAIL_EMAIL,
    MAIL_PASSWORD,
    SECRET: JwtSecret,
    JWT_EXPIRE_IN_MIN: JwtExpireInMin,
    FE_URL,
    RAZORPAY_KEY_ID,
    RAZORPAY_KEY_SECRET,
    ENCRYPTION_KEY,
    ENCRYPTION_IV,
    ENCRYPTION
} = process.env

export {
    DB_USERNAME,
    DB_PASSWORD,
    DB_NAME,
    MAIL_EMAIL,
    MAIL_PASSWORD,
    JwtSecret,
    JwtExpireInMin,
    FE_URL,
    RAZORPAY_KEY_ID,
    RAZORPAY_KEY_SECRET,
    ENCRYPTION_KEY,
    ENCRYPTION_IV,
    ENCRYPTION
}